INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (1, N'Ido                 ', N'0505205066', N'Israel              ', 0, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (2, N'Yossi               ', N'0501112223', N'Israel              ', 1, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (3, N'Emma                ', N'5551234567', N'United Kingdom      ', 3, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (4, N'Hans                ', N'0301234567', N'Germany             ', 2, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (5, N'Sarah               ', N'4167896543', N'Canada              ', 1, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (6, N'Ben                 ', N'0521112345', N'Israel              ', 3, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (7, N'Alice               ', N'7895551234', N'United States       ', 2, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (8, N'Tom                 ', N'0714567890', N'United Kingdom      ', 0, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (9, N'Greta               ', N'0407891234', N'Germany             ', 0, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (10, N'Avi                 ', N'0520001111', N'Israel              ', 1, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (11, N'avi                 ', N'0123451234', N'Israel              ', 2, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (12, N'ido                 ', N'0123451234', N'Israel              ', 2, NULL)
INSERT INTO [dbo].[TblPlayers] ([Id], [Name], [Phone], [Country], [NumOfGames], [Dates]) VALUES (13, N'tom                 ', N'0714567890', N'United Kingdom      ', 0, NULL)
